### ISSUE TITLE
Feature: require a configurable label to exist on a linked issue

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mtfoley/pr-compliance-action#311]
### Is your feature request related to a problem? Please describe.

Forking from https://github.com/JoshuaKGoldberg/template-typescript-package/issues/23: folks sometimes misunderstand the "accepting PRs" label concept and send a PR for an issue not yet ready to accept one. That's a situation I'd like an action to post about on PRs.

### Describe the solution you'd like

It'd be nice if we could have an option pair like:

- `required-issue-labels`: Optional `string[]` of labels that must be on a linked issue
- `required-issue-labels-comment`: Optional `string` text to post when require issue label(s) are missing on a linked issue

The compliance bot should post an informative message when that happens.

### Describe alternatives you've considered

I could do it myself, but it'd be nice to have it here 🤔 

### Additional context

I'd be very happy to send this as a feature!

**Comment by mtfoley** [comment]
Hey @JoshuaKGoldberg happy to accept a PR. I assigned this issue to you. One thing to think about would be whether it's appropriate to auto-close the PR on a failing check (I feel it should be available as behavior, but I'm not sure whether it should be a default).

**Comment by mtfoley** [comment]
So far as I've played with the branch, two things to note:
- we probably need the data fetch for labels in a try/catch. as-is this code dies on a private repo because fetching the linked issue apparently is not allowed, and so the workflow fails with an error (e.g. "resource not available through integration"). this would need to be covered in docs, and the sane default would probably be to *not* complain about issue labels on private repos.
- when you look at the action log, you should see a log message like "{labelsOnIssue:[...]}"

**Comment by mtfoley** [comment]
Branch has been updated to reflect `body-regex` fixes from @RebeccaStevens.
https://github.com/mtfoley/pr-compliance-action/tree/check-issue-labels

**Comment by JoshuaKGoldberg** [comment]
👋 ping @mtfoley - is this something you're still interested in?

**Comment by mtfoley** [comment]
Thanks for the pr @JoshuaKGoldberg! I'm going to munge through some dependabot updates and a cut a release in the next little bit!
